import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import bg from "@/utils/bg.svg";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Apiz Link's",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Toaster richColors />
				<div
					className="bg-neutral-900 min-h-screen"
					style={{
						backgroundImage: `url(${bg.src})`,
						backgroundSize: "cover",
						backgroundPosition: "center",
						backgroundRepeat: "no-repeat",
					}}
				>
					{children}
				</div>
			</body>
		</html>
	);
}
